credentials:
  usernames:
    admin:
      email: admin@mail.com
      name: Admin
      password: $2b$12$5izOFEZMdT4eNUa8lHeb2OtY60QLXUM6otvvIFfVBTVmyt5aW6Nrm # To be replaced with hashed password
cookie:
  expiry_days: 30
  key: SKDJ9km92eks # Must be string
  name: attendance_key
preauthorized:
  emails:
  - starlai@gmail.com